apiVersion: apps/v1
kind: Deployment
metadata:
  name: tamatem-takehome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tamatem-takehome
  template:
    metadata:
      labels:
        app: tamatem-takehome
    spec:
      containers:
        - name: tamatem-takehome
          image: zsaee060/tamatem-takehome:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: tamatem-takehome
spec:
  selector:
    app: tamatem-takehome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
